### PR TITLE
Tolerate out of range gamma changes

### PR DESCRIPTION
**Pull request by deoxal**
This will let a shortcut using the lower or raise options to always reach 1000K or 25000K.

### CODE REVIEW

**Review by terminalforlife — COMMENTED** [review]
Why would you _want_ the values to go out of range? If you whack it out of range, you won't know for who knows how long, needlessly saving an invalid temperature. I'm confused. :\ Remember, Redshifter is intended for use primarily by keyboard shortcuts.

How about including an option to allow for out-of-range usage? I don't mind doing this, if you like the sounds of it.

**Comment by terminalforlife** [comment]
Closing the PR as it's no longer valid, but I've incorporated what you were wanting, per my above post. So just use `-F` or `--force` so you can use any value you like.

**Comment by deoxal** [comment]
That would be a cleaner solution, but now it seems like running it without -F makes it always say "Temperature must be between 1000K and 25000K" or "Minimum gamma available is 1000 at /usr/bin/redshifter line 108" without changing the screen color and when I do run it with -F it seems to behave like your original version.

 I don't really know Perl so made the fewest changes possible to make it work.

**Comment by terminalforlife** [comment]
Try to `reset` the value, or remove the '~/.config/rs-gamma' file. You're getting that error because the 'buffer' is storing the out-of-range data. If using `reset` makes it still give the error, then I'll address that ASAP.

**Comment by terminalforlife** [comment]
Let me know if that works for you. Testing it on my end and it worked fine, both normally and by using out-of-range values. Using reset even on an out-of-range value still works, thankfully.

That said, I've not accounted for the minus character in the integer tests, so I'll have to sort that, now that Redshifter allows such values.

**Comment by terminalforlife** [comment]
TBH, Redshifter being so small and unassuming, should really be in BASH or better yet, Bourne Shell. My thinking at the time, when I opted to rewrite the old Shell version into Perl, was that it would be fast, but what I hadn't considered, is that executing Perl over and over again isn't actually the fastest of actions, despite it executing Perl code comparatively very fast.

**Comment by deoxal** [comment]
I don't know why but I can't install this alternate version when I had no issue installing the orginal version. Here's what it says:

    chmod: cannot access 'redshifterA': No such file or directory
    chown: cannot access 'redshifterA': No such file or directory
    mv: cannot stat 'redshifterA': No such file or directory

All I did is change the name of the file that the content of wget gets written to so I don't have to uninstall my current version. I was able to install it by creating the file manually and giving it the right permissions though. Still if I run

    redshifterA reset
    redshifterA -F lower 10000

the Gamma ramp does not change at all. I created another action in redshifter to print the value of $Temp and it's actually -3500 now.

**Comment by terminalforlife** [comment]
How are you installing it? Using Cito? Debian package? Manually?

**Comment by deoxal** [comment]
I used the wget one liner provided on the mint forum, I'm Scysograph. I haven't set up backups on my system and when I tried copying it to my dekstop I got permissions issues moving it back. So I opted to run this, this time
    wget -nv https://raw.githubusercontent.com/terminalforlife/PerlProjects/master/source/redshifter && { chmod 755 redshifterA; chown 0:0 redshifterA; sudo mv -n redshifterA /usr/bin/; }

Since that didn't work I created the file /usr/bin/redshifterA and pasted the code into it, then ran **chmod 755 redshifterA** and **chown 0:0 redshifterA**

I never wanted to give negative values to set, lower, or raise. Which is why my change doesn't allow for negative values, it just makes it so **redshifter lower 30000** completes and without setting $Temp to a negative value. Yes that's the same as redshifter set 1000 but my shortcuts uses lower and raise for a smooth transition.

**Comment by terminalforlife** [comment]
Ah, okay. Since you removed the code for checking the values within the function which checks the values, I assumed you hadn't otherwise added a check somewhere else.

The WGet install thing wasn't working is because WGet was downloading and storing a file called 'redshifter', not 'redshifterA'. For future reference, you can override this with:

```
wget -nv -O redshifterA https://raw.githubusercontent.com/terminalforlife/PerlProjects/master/source/redshifter
```

**Comment by terminalforlife** [comment]
I changed `print()` to `warn()` since it's an error, but `warn()` doesn't exit.

**Comment by deoxal** [comment]
Oh I see how I messed up the spacing now. I always obsessed over getting the spacing right in my first CS class but Eclipse helped out.

We were writing Java then and everything was in a class so the final curly brace was always at the end of the file. That's what tripped me up here, I was confused why the diff said I deleted a curly brace but the code compiled and I wasn't able to make it crash so I thought I was set.

**Comment by terminalforlife** [comment]
So, is everything working on your end now? You're happy with the result?

**Comment by deoxal** [comment]
I'll know when I get home from work, I work 2nd shift Eastern time.

I know I didn't miss the curly brace but the diff said I removed one. I was trying to keep the spacing nice, my story about my class in Java was how I messed it up this time.

What helps me keep these } alligned though is placing the { on a new line.

**Comment by terminalforlife** [comment]
Ah. By using tabs, I never really need to worry about alignment, as it's much easier to see the difference. I find with whitespaces it's a lot easier to misalign stuff.

**Pull request merged**
